<header x-data="{ mobileMenu: false }" class="sticky top-0 z-40 border-b border-slate-200/80 bg-white/85 backdrop-blur-xl dark:border-slate-800/80 dark:bg-slate-950/85">
<div class="flex h-20 items-center justify-between px-4 sm:px-6 lg:px-8">
<div class="flex items-center gap-3"><button @click="mobileMenu=!mobileMenu" class="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-600 hover:bg-slate-100 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800 lg:hidden"><span x-text="mobileMenu ? '✕' : '☰'"></span></button><div><p class="hidden text-xs font-medium text-slate-400 sm:block">{{ now()->format('l, M d, Y') }}</p><h1 class="text-lg font-black tracking-tight">@yield('heading','Dashboard')</h1></div></div>
<div class="flex items-center gap-2">
<button class="hidden h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-sm font-medium text-slate-500 hover:border-indigo-300 hover:text-indigo-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-400 sm:flex">⌕ <span>Search</span><kbd class="rounded-md bg-slate-100 px-1.5 py-0.5 text-[10px] dark:bg-slate-800">/</kbd></button>
<button @click="darkMode=!darkMode" class="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-600 hover:bg-slate-100 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800"><span x-show="!darkMode">☾</span><span x-show="darkMode">☀</span></button>
<button @click="language=language==='fa'?'en':'fa'" class="hidden h-10 min-w-12 rounded-xl border border-slate-200 px-3 text-xs font-bold text-slate-600 hover:bg-slate-100 dark:border-slate-700 dark:text-slate-300 sm:block"><span x-text="language==='fa'?'EN':'FA'"></span></button>
<button class="relative grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-600 hover:bg-slate-100 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800">♢<span class="absolute end-2 top-2 h-2 w-2 rounded-full bg-indigo-500 ring-2 ring-white dark:ring-slate-950"></span></button>
<a href="{{ url('/profile') }}" class="ms-1 flex items-center gap-2 rounded-xl p-1 hover:bg-slate-100 dark:hover:bg-slate-800"><div class="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 text-sm font-black text-white">R</div><div class="hidden text-start sm:block"><p class="text-xs font-bold">Reza</p><p class="text-[10px] text-slate-400">Free Plan</p></div></a>
</div></div>
<div x-show="mobileMenu" x-cloak x-transition class="border-t border-slate-200 bg-white px-4 py-4 dark:border-slate-800 dark:bg-slate-950 lg:hidden"><nav class="grid gap-1 sm:grid-cols-2"><a href="{{url('/dashboard')}}" class="rounded-xl px-4 py-3 text-sm font-bold hover:bg-indigo-50 dark:hover:bg-indigo-500/10">⌂ &nbsp; Dashboard</a><a href="{{url('/tasks')}}" class="rounded-xl px-4 py-3 text-sm font-bold hover:bg-indigo-50 dark:hover:bg-indigo-500/10">✓ &nbsp; Tasks</a><a href="{{url('/calendar')}}" class="rounded-xl px-4 py-3 text-sm font-bold hover:bg-indigo-50 dark:hover:bg-indigo-500/10">▣ &nbsp; Calendar</a><a href="{{url('/categories')}}" class="rounded-xl px-4 py-3 text-sm font-bold hover:bg-indigo-50 dark:hover:bg-indigo-500/10"># &nbsp; Categories</a><a href="{{url('/statistics')}}" class="rounded-xl px-4 py-3 text-sm font-bold hover:bg-indigo-50 dark:hover:bg-indigo-500/10">◒ &nbsp; Statistics</a><a href="{{url('/profile')}}" class="rounded-xl px-4 py-3 text-sm font-bold hover:bg-slate-100 dark:hover:bg-slate-800">◎ &nbsp; Profile</a><a href="{{url('/settings')}}" class="rounded-xl px-4 py-3 text-sm font-bold hover:bg-slate-100 dark:hover:bg-slate-800">⚙ &nbsp; Settings</a></nav></div>
</header>