@extends('layouts.app')
@section('title','Statistics — DoNext')
@section('heading','Statistics')
@section('content')
<div class="space-y-6">
<section><p class="mb-2 text-sm font-semibold text-indigo-600 dark:text-indigo-400">تصویر کلی عملکرد</p><h2 class="text-3xl font-black sm:text-4xl">آمار و گزارش‌ها</h2><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">پیشرفت و روند انجام کارهایت را بررسی کن.</p></section>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach([['کل کارها','65','+12%'],['انجام شده','42','+18%'],['در انتظار','17','-5%'],['نرخ تکمیل','72%','+8%']] as $s)<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-bold text-slate-400">{{$s[0]}}</p><div class="mt-3 flex items-end justify-between"><span class="text-3xl font-black">{{$s[1]}}</span><span class="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-400">{{$s[2]}}</span></div></div>@endforeach</div>
<div class="grid gap-6 lg:grid-cols-5"><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:col-span-3 dark:border-slate-800 dark:bg-slate-900"><div class="flex items-center justify-between"><div><h3 class="font-black">فعالیت هفتگی</h3><p class="mt-1 text-xs text-slate-400">کارهای تکمیل شده</p></div><span class="rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold dark:bg-slate-800">این هفته</span></div><div class="mt-8 flex h-64 items-end justify-between gap-3">@foreach([45,68,52,84,62,92,72] as $n)<div class="flex h-full flex-1 flex-col justify-end gap-2"><div class="rounded-t-xl bg-indigo-500 transition hover:bg-indigo-600" style="height:{{$n}}%"></div><span class="text-center text-[10px] text-slate-400">{{['ش','ی','د','س','چ','پ','ج'][$loop->index]}}</span></div>@endforeach</div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:col-span-2 dark:border-slate-800 dark:bg-slate-900"><h3 class="font-black">وضعیت کارها</h3><div class="mx-auto my-8 grid h-44 w-44 place-items-center rounded-full bg-[conic-gradient(#4f46e5_0_65%,#f59e0b_65%_85%,#e2e8f0_85%_100%)]"><div class="grid h-28 w-28 place-items-center rounded-full bg-white dark:bg-slate-900"><span class="text-2xl font-black">65%</span></div></div><div class="space-y-3 text-xs font-semibold"><div class="flex justify-between"><span>● تکمیل شده</span><span>65%</span></div><div class="flex justify-between"><span>● در حال انجام</span><span>20%</span></div><div class="flex justify-between"><span>● باقی‌مانده</span><span>15%</span></div></div></section></div>
</div>
@endsection