<!DOCTYPE html>
<html lang="fa" dir="rtl" x-data="{ darkMode: localStorage.getItem('theme') === 'dark', language: localStorage.getItem('language') || 'fa' }" x-init="document.documentElement.classList.toggle('dark', darkMode); document.documentElement.dir = language === 'fa' ? 'rtl' : 'ltr'; $watch('darkMode', value => { localStorage.setItem('theme', value ? 'dark' : 'light'); document.documentElement.classList.toggle('dark', value); }); $watch('language', value => { localStorage.setItem('language', value); document.documentElement.dir = value === 'fa' ? 'rtl' : 'ltr'; window.dispatchEvent(new CustomEvent('language-changed', {detail:{language:value}})); })" class="scroll-smooth">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="csrf-token" content="{{ csrf_token() }}"><meta name="theme-color" content="#4f46e5">
<title>@yield('title', 'DoNext')</title>
<script src="https://cdn.tailwindcss.com"></script><script>tailwind.config={darkMode:'class'}</script>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=Vazirmatn:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
<style>body{font-family:Vazirmatn,Inter,sans-serif}[x-cloak]{display:none!important}::selection{background:rgb(99 102 241/.2)}:focus-visible{outline:3px solid rgb(99 102 241/.45);outline-offset:2%}</style>
<script>
window.DoNextI18n={
 fa:{
 'Dashboard':'داشبورد','Tasks':'کارها','Calendar':'تقویم','Categories':'دسته‌بندی‌ها','Statistics':'آمار','Profile':'پروفایل','Settings':'تنظیمات','Workspace':'فضای کاری','Personal':'شخصی','Get things done.':'کارها را انجام بده.','Free Plan':'پلن رایگان','Search':'جستجو','Notifications':'اعلان‌ها','3 new':'۳ جدید','Search tasks':'جستجوی کارها','Today':'امروز','Tomorrow':'فردا','Pending':'در انتظار','Completed':'انجام شده','All':'همه','High':'زیاد','Medium':'متوسط','Low':'کم','New Task':'کار جدید','Add Task':'افزودن کار','Create Task':'ایجاد کار','Task Details':'جزئیات کار','Categories':'دسته‌بندی‌ها','Statistics':'آمار و گزارش‌ها','Settings':'تنظیمات','Profile':'پروفایل','English':'انگلیسی','Persian':'فارسی','Light':'روشن','Dark':'تیره','System':'سیستم','Save Changes':'ذخیره تغییرات','Cancel':'انصراف','Confirm':'تأیید','Edit':'ویرایش','Delete':'حذف','Back':'بازگشت','Month':'ماه','Week':'هفته','Day':'روز','This Week':'این هفته','This Month':'این ماه','No tasks found':'کاری پیدا نشد','Total Tasks':'کل کارها','Completed Tasks':'کارهای انجام‌شده','Completion Rate':'نرخ تکمیل','Login':'ورود','Register':'ثبت‌نام','Sign in':'ورود','Sign up':'ثبت‌نام','Password':'رمز عبور','Email':'ایمیل','Name':'نام','Remember me':'مرا به خاطر بسپار','Forgot password?':'فراموشی رمز عبور؟','Create account':'ساخت حساب','Welcome back':'خوش آمدی','Due date':'موعد','Description':'توضیحات','Priority':'اولویت','General':'عمومی','Appearance':'ظاهر','Security':'امنیت','Language':'زبان','Time zone':'منطقه زمانی','Notifications':'اعلان‌ها','Get started':'شروع کنید'
 },
 en:{
 'داشبورد':'Dashboard','کارها':'Tasks','تقویم':'Calendar','دسته‌بندی‌ها':'Categories','آمار':'Statistics','پروفایل':'Profile','تنظیمات':'Settings','فضای کاری':'Workspace','شخصی':'Personal','کارها را انجام بده.':'Get things done.','پلن رایگان':'Free Plan','جستجو':'Search','اعلان‌ها':'Notifications','۳ جدید':'3 new','جستجوی کارها':'Search tasks','امروز':'Today','فردا':'Tomorrow','در انتظار':'Pending','انجام شده':'Completed','همه':'All','زیاد':'High','متوسط':'Medium','کم':'Low','کار جدید':'New Task','افزودن کار':'Add Task','ایجاد کار':'Create Task','جزئیات کار':'Task Details','آمار و گزارش‌ها':'Statistics & Reports','ذخیره تغییرات':'Save Changes','انصراف':'Cancel','تأیید':'Confirm','ویرایش':'Edit','حذف':'Delete','بازگشت':'Back','ماه':'Month','هفته':'Week','روز':'Day','این هفته':'This Week','این ماه':'This Month','کاری پیدا نشد':'No tasks found','کل کارها':'Total Tasks','کارهای انجام‌شده':'Completed Tasks','نرخ تکمیل':'Completion Rate','ورود':'Login','ثبت‌نام':'Register','رمز عبور':'Password','ایمیل':'Email','نام':'Name','مرا به خاطر بسپار':'Remember me','فراموشی رمز عبور؟':'Forgot password?','ساخت حساب':'Create account','خوش آمدی':'Welcome back','موعد':'Due date','توضیحات':'Description','اولویت':'Priority','عمومی':'General','ظاهر':'Appearance','امنیت':'Security','زبان':'Language','منطقه زمانی':'Time zone','شروع کنید':'Get started','مدیریت کارها':'Task Management','کارهای من':'My Tasks','لیست کارها':'Task List','۱۲ کار در لیست':'12 tasks in the list','این فرم فعلاً فقط رابط کاربری است.':'This form is UI only for now.','عنوان کار':'Task title','توضیحات کار...':'Task description...','صفحه پیدا نشد':'Page not found','صفحه مورد نظر وجود ندارد یا جابه‌جا شده است.':'The page you are looking for does not exist or has moved.','بازگشت به داشبورد':'Back to Dashboard','دسته جدید':'New Category','ایجاد دسته':'Create Category','فقط رابط کاربری':'UI only','فعالیت هفتگی':'Weekly Activity','وضعیت کارها':'Task Status','اطلاعات شخصی':'Personal Information','فعالیت':'Activity','تغییر رمز عبور':'Change password','تکمیل پروژه Laravel':'Complete Laravel project','مطالعه Livewire':'Study Livewire','طراحی داشبورد DoNext':'Design DoNext dashboard','ساخت صفحه Calendar':'Build Calendar page','بهبود نسخه موبایل':'Improve mobile version','دوشنبه':'Monday','سه‌شنبه':'Tuesday','چهارشنبه':'Wednesday','پنجشنبه':'Thursday','جمعه':'Friday','شنبه':'Saturday','یکشنبه':'Sunday'
 }};
(function(){
 function translate(root=document){const lang=localStorage.getItem('language')||'fa'; const map=DoNextI18n[lang]||{}; const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT); const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode); nodes.forEach(n=>{if(n.parentElement && ['SCRIPT','STYLE'].includes(n.parentElement.tagName))return; const raw=n.nodeValue; const trimmed=raw.trim(); if(trimmed&&map[trimmed]) n.nodeValue=raw.replace(trimmed,map[trimmed]);}); document.querySelectorAll('[placeholder]').forEach(el=>{const key=el.dataset.i18nPlaceholder||el.getAttribute('placeholder'); if(map[key]){el.dataset.i18nPlaceholder=key;el.setAttribute('placeholder',map[key]);}}); document.querySelectorAll('option').forEach(el=>{const key=el.dataset.i18nText||el.textContent.trim(); if(map[key]){el.dataset.i18nText=key;el.textContent=map[key];}}); document.documentElement.lang=lang; document.documentElement.dir=lang==='fa'?'rtl':'ltr';}
 window.DoNextTranslate=translate; document.addEventListener('DOMContentLoaded',()=>{translate(); new MutationObserver(()=>translate()).observe(document.body,{childList:true,subtree:true});}); window.addEventListener('language-changed',()=>setTimeout(translate,0));
})();
</script>
<script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
@livewireStyles
</head>
<body class="min-h-screen bg-slate-50 text-slate-900 antialiased transition-colors duration-300 dark:bg-slate-950 dark:text-white">
<div class="min-h-screen"><x-sidebar/><div class="min-h-screen lg:ms-72"><x-navbar/><main class="min-h-[calc(100vh-5rem)] p-4 sm:p-6 lg:p-8">{{ $slot ?? '' }}@yield('content')</main></div></div>
<x-toast/><x-confirm-modal/>
@livewireScripts
</body></html>